const ADD_TODO = "ADD_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const DELETE_TODO = "DELETE_TODO";
const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
const TOGGLE_TODO = "TOGGLE_TODO";

export { ADD_TODO, UPDATE_TODO, DELETE_TODO, UPDATE_USER_DETAILS, TOGGLE_TODO };
